curl 
-X POST https://api.openai.com/v1/chat/completions HTTP/1.1
header Content-Type: application/json
header Authorization: "Bearersk-lw8nLA78oGquqMbegD8dT3BlbkFJybdu1w3FzAl6PqN22BmC"

{
    "model":"gpt-3.5-turbo",
    "messages":[{
        "role": "user",
        "content": "你好"
    }]
}

### 

curl -X POST https://api.chatanywhere.com.cn/v1/chat/completions HTTP/1.1
-H "Content-Type: application/json"
-H "Authorization: Bearer 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"

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "你好"
    }
  ]
}

### 
POST https://api.openai.com/v1/chat/completions HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "你好"
    }
  ]
}

### 

POST https://api.chatanywhere.com.cn/chat/completions HTTP/1.1
Content-Type: application/json
Authorization: Bearer sk-7pJKKhJiLTstfIrsMkjIwhh0pgSjMS31ktYJB9mhEp9X6gTY

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "你好"
    }
  ]
}